
DROP TABLE WALLET CASCADE CONSTRAINT;
DROP TABLE VM CASCADE CONSTRAINT;
DROP TABLE USER_BC CASCADE CONSTRAINT;
DROP TABLE RESULT CASCADE CONSTRAINT;
drop sequence WALLET_IDX;  
drop sequence result_IDX;  


CREATE TABLE USER_BC(
      USER_ID   VARCHAR2(30) PRIMARY KEY,
      PWD         VARCHAR2(30) NOT NULL,
      EMAIL      VARCHAR2(50) NOT NULL,
      DEPOSIT   NUMBER(38)    DEFAULT 0
      );
CREATE TABLE VM(
   VM_IDX         NUMBER(10) PRIMARY KEY,
   VM_P            NUMBER(10) NOT NULL
);
      
CREATE TABLE WALLET(
      WALLET_IDX   NUMBER(20) PRIMARY KEY,
      VM_IDX         NUMBER(20) NOT NULL REFERENCES VM(VM_IDX),
      PRICE         NUMBER(20) NOT NULL,
      AMOUNT         NUMBER(10) NOT NULL,
      SUM            NUMBER(38) NOT NULL,
      USER_ID      VARCHAR(30) NOT NULL REFERENCES USER_BC(USER_ID)       
      );
create sequence WALLET_IDX start with 1 increment BY 1;      

CREATE TABLE RESULT(
   RESULT_IDX      NUMBER(20) PRIMARY KEY,
      USER_ID         VARCHAR2(30) REFERENCES USER_BC(USER_ID), 
      AMOUNT_SUM      NUMBER(38) DEFAULT 0,
      PRE_VAL         NUMBER(38) DEFAULT 0,
      C_VAL            NUMBER(38) DEFAULT 0,
      RATE               NUMBER(20) DEFAULT 0
      );
      
create sequence RESULT_IDX start with 1 increment BY 1; 

INSERT INTO VM VALUES (0,50);


select * from result